### PR TITLE
chore: Update CN proto to 0.65.0-rc1

### LINKED ISSUE #1386: chore(protobuf): Update BN to use latest version of CN protobuf.
### Story Form

As a BN Developer
I want to stay up to date on Proto Spec from CN
So that we implement timely the Spec up to `0.64.x`

### Technical Notes

Once `0.64.x` is released, we should adopt the new protobuf spec, for that we need to update the commit hash of the CN repo that we are using.

see issue #1377 for reference

### LINKED ISSUE #1525: BN `0.17.0-rc1` and `0.16.1` are not compatible with CN `0.65.0-rc1` due to CN Proto Spec Mismatch
### Description

Consensus Node is using a new BlockStream Protobuf Spec hence when BN attempts to do Parse of some objects, it encounters a ParseException.

### Steps to Reproduce

Follow the guide for running solo e2e with CN BN and MN integrated.

### Additional context

There were already a related Issue and a draft PR.

https://github.com/hiero-ledger/hiero-block-node/pull/1408
https://github.com/hiero-ledger/hiero-block-node/issues/1386

### PR DESCRIPTION
**Pull request by Nana-EC**
## Reviewer Notes

CN proto was update to 0.65.0-rc1 and contains notable updates around TraceData and other items

- Bump CN proto to 0.65.0-rc1 in git clone gradle task
- Add export for `com.hedera.hapi.block.stream.trace` in `block-node/protobuf-pbj/src/main/java/module-info.java` to ensure classes are available
- Add export for  `com.hedera.hapi.block.stream.trace.protoc` to `tools-and-tests/protobuf-protoc/src/main/java/module-info.java` to ensure classes are available

## Related Issue(s)
Fixes #1386 
Fixes #1525

**Note for reviewers**
Once there's a 0.65.0 tag we can easily update the hash and there shouldn't be other changes but it's worthwhile to get this fixed to unblock testing with Solo

I'm still investigating the UT failure below. Can't seem to repro it locally 
```
* What went wrong:
Execution failed for task ':protobuf-protoc:compileJava'.
> Compilation failed; see the compiler output below.
  /home/runner/_work/hiero-block-node/hiero-block-node/tools-and-tests/protobuf-protoc/src/main/java/module-info.java:12: error: package is empty or does not exist: com.hedera.hapi.block.stream.trace.protoc
      exports com.hedera.hapi.block.stream.trace.protoc;
                                                ^
  1 error
```

### CODE REVIEW

**Review by ata-nas — DISMISSED** [review]

File: tools-and-tests/protobuf-protoc/src/main/java/module-info.java [hunk 1]
```diff
@@ -9,6 +9,7 @@
     exports com.hedera.hapi.block.stream.protoc;
     exports com.hedera.hapi.block.stream.input.protoc;
     exports com.hedera.hapi.block.stream.output.protoc;
+    exports com.hedera.hapi.block.stream.trace.protoc;
```
Comment (jsync-swirlds) [inline tools-and-tests/protobuf-protoc/src/main/java/module-info.java:12]: This is not correct and breaks the build.
We should check, the last portion might be `legacy`.

**Review by jsync-swirlds — CHANGES_REQUESTED** [review]
Build is broken at the moment due to a module info error.

File: tools-and-tests/protobuf-protoc/src/main/java/module-info.java (hunk 1 above)
Comment (AlfredoG87) [reply tools-and-tests/protobuf-protoc/src/main/java/module-info.java:12]: The aim is to address this on the current sprint and have it merged for `0.16` release

**Comment by Nana-EC** [comment]
Moving to draft whiles I work on updating it to support `v0.65.0-rc1`

**Review by AlfredoG87 — APPROVED** [review]

**Review by nathanklick — APPROVED** [review]
